inherit_from:
  - .rubocop_airbnb.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'path/ruby'
    # Do not use block commentsを回避するため
    - 'spec/spec_helper.rb'
    # Redundant self detected.を回避するため
    - 'app/models/article.rb'
    # Avoid default_scopeを回避するため
    - 'app/models/notification.rb'
    # Don't repeat examples within an example groupを回避するため
    - 'spec/models/room_spec.rb'
    # Slash continuation should be reserved for closed string continuation. Many times it is used to get around other existing rulesを回避するため
    - 'spec/support/actiontext_helper.rb'
    
# コメントに日本語許可
Style/AsciiComments:
  Enabled: false
# 一行の文字数の上限を８０文字から200文字へ変更
LineLength:
  Max: 200
